### ISSUE TITLE
When opened with photopea, and after using save, when right click again, Mask editor node disappears, does not use photopea, Mask editor node exist?

### ISSUE THREAD

**Issue by shumoLR** [coolzilj/ComfyUI-Photopea#5]
Hello, thank you very much, during the use of this problem:
When opened with photopea, and after using save, when right click again, Mask editor node disappears, does not use photopea, Mask editor node exist? What is the reason for this? thank you。
This is before use：
![image](https://github.com/coolzilj/ComfyUI-Photopea/assets/169419160/81b9652f-0559-4759-9c37-7cc797e0e7f6)
This is after use：
![image](https://github.com/coolzilj/ComfyUI-Photopea/assets/169419160/fb7b3398-e097-465d-9119-409c787970b9)

**Comment by enduro** [comment]
After Photopea Editor is opened (no matter if Canceled or Saved) MaskEditor disappears from all nodes. Refresh browser tab restores MaskEditor option until Photopea opened again.

**Comment by MNeMoNiCuZ** [comment]
This is still an issue. It makes it very hard to work with Photopea.

**Comment by bananasss00** [comment]
fixed in PR https://github.com/coolzilj/ComfyUI-Photopea/pull/13

i am paste fix from impact pack https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/348c3dcb6b3f9e5fe42f184a01df0bb22b7bfc8d/js/impact-sam-editor.js#L279

**Comment by MNeMoNiCuZ** [comment]
Great job! Thanks for contributing!

**Comment by MarcelMoczarski** [comment]
another fix: replace the close() function (line 182) with this one:

```
close() {
  if (typeof ComfyApp.onClipspaceEditorClosed === "function") {
    ComfyApp.onClipspaceEditorClosed();   
  } else {
    ComfyApp.clipspace_return_node = null;  
  }

  if (this.iframe_container &&
      this.element.contains(this.iframe_container)) {
    this.element.removeChild(this.iframe_container);
  }

  super.close();  
}

```

**Comment by dz86** [comment]
thank you

**Comment by enthusiastaiuser-ai** [comment]
This may be a very late question to ask as I still facing this issue, I see some helpful people have already provided some solutions up there. However I still don't know how to fix this issue. I am not really that tech-savvy therefore I don't know how to use the solutions above to fix my problem. So far I have only copy and pasted the impact-sam-editor.js file in my comfyui but it seems like it did not solve the problem. If anyone can clear this up for me, thank you in advance.

**Comment by enthusiastaiuser-ai** [comment]
Well, after a while of thinking I figured out, instead of playing around the impact-sam-editor.js file, you have to go to the custom node file and find the photopea file, then open it's js file (which should only be one). Find these texts below
```
close() {
    this.element.removeChild(this.iframe_container);
    super.close();
  }
```

and then replace them with these 
```
close() {
  if (typeof ComfyApp.onClipspaceEditorClosed === "function") {
    ComfyApp.onClipspaceEditorClosed();   
  } else {
    ComfyApp.clipspace_return_node = null;  
  }

  if (this.iframe_container &&
      this.element.contains(this.iframe_container)) {
    this.element.removeChild(this.iframe_container);
  }

  super.close();  
}
```
save the file and restart comfyui, and it should work. Thank you for providing this line of code really appreciated.
